-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 13:08:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`platenlabel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`platenlabel` (
  `id` INT(11) NULL,
  `naam` VARCHAR(255) NULL,
  `locatie` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artiesten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artiesten` (
  `id` INT(11) NULL,
  `artiesten naam` VARCHAR(255) NULL,
  `voornaam` VARCHAR(255) NULL,
  `achternaam` VARCHAR(255) NULL,
  `geboortedatum` DATE NULL,
  `platenlabel_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_artiesten_platenlabel1_idx` (`platenlabel_id` ASC),
  CONSTRAINT `fk_artiesten_platenlabel1`
    FOREIGN KEY (`platenlabel_id`)
    REFERENCES `mydb`.`platenlabel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`studio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`studio` (
  `id` INT(11) NULL,
  `naam` VARCHAR(255) NULL,
  `locatie` VARCHAR(255) NULL,
  `apparatuur` VARCHAR(255) NULL,
  `software` VARCHAR(255) NULL,
  `artiesten_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `artiesten_id`),
  INDEX `fk_studio_artiesten_idx` (`artiesten_id` ASC),
  CONSTRAINT `fk_studio_artiesten`
    FOREIGN KEY (`artiesten_id`)
    REFERENCES `mydb`.`artiesten` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`album` (
  `id` INT NULL AUTO_INCREMENT,
  `naam` VARCHAR(255) NULL,
  `artiesten_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `artiesten_id`),
  INDEX `fk_album_artiesten1_idx` (`artiesten_id` ASC),
  CONSTRAINT `fk_album_artiesten1`
    FOREIGN KEY (`artiesten_id`)
    REFERENCES `mydb`.`artiesten` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
