-- MySQL Script generated by MySQL Workbench
-- Tue Mar 21 13:09:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stardunk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stardunk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stardunk` DEFAULT CHARACTER SET utf8 ;
USE `stardunk` ;

-- -----------------------------------------------------
-- Table `stardunk`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stardunk`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_type_code` INT NULL,
  `supplier_id` INT NULL,
  `product_name` VARCHAR(45) NULL,
  `product_price` INT NULL,
  `other_product_details` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
